.github/workflows/test.yml
README.md
package.json
src/assets/styles/_bootstrap-customized.scss
src/i18n.ts
src/sections/hello-dataverse/HelloDataverse.tsx
src/sections/ui/navbar/Navbar.tsx
src/sections/ui/navbar/NavbarProps.ts
tests/sections/layout/header/Header.test.tsx
tests/sections/ui/navbar/Navbar.test.tsx
tests/sections/ui/navbar/nav-dropdown/NavDropdown.test.tsx
vitest.config.ts

This PR adds the test coverage check to the Github actions to maintain the unit tests coverage of the repo at 95%, checking it on push. It also adds the missing tests needed to reach this 95% coverage, in fact, with the new tests added we have reached 100% coverage
https://coveralls.io/github/IQSS/dataverse-frontend  
- Closes https://github.com/IQSS/dataverse-frontend/issues/19
To generate the coverage report I used [c8 with Vitest](https://vitest.dev/guide/coverage.html), because it was really easy to set up, the coverage check can be set in the `vitest.config.ts` file. It generates the report in lcov format which then can be uploaded to [Coveralls](https://coveralls.io) using the [coverallsapp Github action](https://github.com/marketplace/actions/coveralls-github-action)
For the …

19 - Tests coverage

---

cypress/component/ui/accordion/Accordion.spec.tsx
src/sections/ui/accordion/Accordion.tsx
src/sections/ui/accordion/AccordionBody.tsx
src/sections/ui/accordion/AccordionHeader.tsx
src/sections/ui/accordion/AccordionItem.tsx
src/sections/ui/assets/styles/bootstrap-customized.scss
src/stories/ui/accordion/Accordion.stories.tsx
tests/sections/ui/accordion/Accordion.test.tsx
tests/sections/ui/accordion/AccordionItem.test.tsx

Adds an Accordion UI element
- Closes #35
npm run storybook 
no
no

Add accordion element of the design system

---

.github/workflows/deploy-beta-testing.yml
README.md

Adds a GitHub action that is executed on any push event in the develop branch and deploys the application to the remote Beta Testing environment.
- Closes #153 
We need to create the GitHub environment in this repository with the secrets corresponding to the credentials to allow the GitHub action to access and update the Beta Testing instance.
The PR reviewer / QA should contact me to set up this environment, since I have the secrets.
If we set a DNS for the environment before merging this PR, the README URLs will need to be updated.
You can see how the action works in my fork repository, where I have committed several times in the develop branch, causing these events to trigger the action:
https://github.com/GPortas/dataverse-frontend/actions/workflows/deploy-beta-testing.yml
These …

Add Beta Testing Environment deployment Github action

---

.github/workflows/deploy-beta-testing.yml
.github/workflows/deploy.yml

Updates the beta-testing deploy GitHub action to use "flat" GitHub secrets instead of GitHub environments with secrets, since the GitHub organization does not support that feature.
Also updates the action to use payara6 commands.
- Closes #161
New GitHub secrets are already configured by myself in the IQSS/dataverse-frontend repository.
You can see how my fork correctly deploys the application using the implemented changes:
https://github.com/GPortas/dataverse-frontend/actions/runs/5892661657
N/A
No
N/A

Update the beta-testing deploy GitHub action to use "flat" GitHub secrets

---

dev.Dockerfile
package-lock.json
package.json
src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
src/files/domain/repositories/FileRepository.ts
src/files/domain/useCases/getFilesTotalDownloadSize.ts
src/files/infrastructure/FileJSDataverseRepository.ts
src/files/infrastructure/mappers/JSFileMapper.ts
src/info/infrastructure/repositories/DataverseInfoJSDataverseRepository.ts
src/metadata-block-info/infrastructure/repositories/MetadataBlockInfoJSDataverseRepository.ts
src/sections/dataset/dataset-files/DatasetFiles.tsx
src/sections/dataset/dataset-files/files-table/FilesTable.tsx
src/sections/dataset/dataset-files/files-table/row-selection/useFileSelection.ts
src/sections/dataset/dataset-files/files-table/zip-download-limit-message/ZipDownloadLimitMessage.tsx
src/sections/dataset/dataset-files/useFiles.tsx
src/settings/infrastructure/SettingJSDataverseRepository.ts
src/stories/WithSettings.tsx
src/stories/files/FileMockData.ts
src/stories/files/FileMockLoadingRepository.ts
src/stories/files/FileMockNoDataRepository.ts
src/stories/files/FileMockNoFiltersRepository.ts
src/stories/files/FileMockRepository.ts
src/users/infrastructure/repositories/UserJSDataverseRepository.ts
tests/component/sections/dataset/dataset-files/DatasetFiles.spec.tsx
tests/component/sections/dataset/dataset-files/files-table/FilesTable.spec.tsx
tests/component/sections/dataset/dataset-files/files-table/zip-download-limit-message/ZipDownloadLimitMessage.spec.tsx
tests/component/sections/dataset/dataset-files/useFiles.spec.tsx
tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx
tests/e2e-integration/integration/files/FileJSDataverseRepository.spec.ts

This PR integrates the frontend with the getDatasetFilesTotalDownloadSize use case from js-dataverse to get the total download size of the dataset files. This is used in the UI to display the Zip Download Limit Message to the user when they select all rows and the Files Table is paginated.
- Closes #170 
- ZipDownloadLimitMessage component now needs to read the value from the getDatasetFilesTotalDownloadSize use case to correctly display the size of the select files when there Select All button is clicked.
- Integrate js-dataverse use case getDatasetFilesTotalDownloadSize
- Fix an integration test about to get the deaccessioned files from js-dataverse now that js-dataverse has been updated to include the deaccessioned files.
1. Run `npm i` …

170 - Integration files total download size

---

.github/workflows/test.yml

e2e tests have been failing for two months.
- None, but related to #213
This is what we use at https://github.com/gdcc/api-test-runner/blob/main/.github/workflows/develop.yml to dump the logs.
Merge it. Then look at the logs

Dump Docker logs on failure

---

public/locales/en/files.json
src/files/domain/models/File.ts
src/sections/dataset/dataset-files/files-table/FilesTableColumnsDefinition.tsx
src/sections/dataset/dataset-files/files-table/file-actions/FileActionsHeader.module.scss
src/sections/dataset/dataset-files/files-table/file-actions/FileActionsHeader.tsx
src/sections/dataset/dataset-files/files-table/file-actions/download-files/DownloadFilesButton.module.scss
src/sections/dataset/dataset-files/files-table/file-actions/download-files/DownloadFilesButton.tsx
src/sections/dataset/dataset-files/files-table/file-actions/edit-files-menu/EditFilesMenu.tsx
src/sections/dataset/dataset-files/files-table/file-actions/edit-files-menu/EditFilesOptions.tsx
src/sections/dataset/dataset-files/files-table/file-actions/no-selected-files-modal/NoSelectedFilesModal.tsx
src/sections/dataset/dataset-files/files-table/useFilesTable.tsx
src/stories/dataset/dataset-files/files-table/file-actions/download-files/DownloadFilesButton.stories.tsx
src/stories/dataset/dataset-files/files-table/file-actions/edit-files-menu/EditFilesMenu.stories.tsx
tests/component/dataset/domain/models/DatasetMother.ts
tests/component/files/domain/models/FileMother.ts
tests/component/sections/dataset/dataset-files/files-table/file-actions/FileActionsHeader.spec.tsx
tests/component/sections/dataset/dataset-files/files-table/file-actions/download-files/DownloadFilesButton.spec.tsx
tests/component/sections/dataset/dataset-files/files-table/file-actions/edit-files-menu/EditFilesMenu.spec.tsx
tests/component/sections/dataset/dataset-files/files-table/file-actions/edit-files-menu/EditFilesOptions.spec.tsx

This PR add the Download Button to the Files Table. (Only the UI with no backend integration yet)
- Closes #187 
1. Install the necessary dependencies using `npm install`.
5. Build the design system with `cd packages/design-system && npm run build`.
6. Navigate back to the root directory with `cd ../../`.
7. Start Storybook with `npm run storybook`.
8. Visit [the Dataset in the Storybook](http://localhost:6006/?path=/story/pages-dataset--draft-with-all-dataset-permissions) to check that the Download button is being displayed in the Files Table, also check the behaviour about showing the No Selected Files Modal if no files are being selected
Download button added to the Files Table UI

187 - Files table download button

---

package-lock.json
package.json
src/dataset/domain/models/Dataset.ts
src/dataset/infrastructure/mappers/JSDatasetMapper.ts
src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
src/sections/dataset/dataset-action-buttons/edit-dataset-menu/EditDatasetMenu.tsx
src/sections/dataset/dataset-action-buttons/publish-dataset-menu/PublishDatasetMenu.tsx
src/sections/dataset/dataset-action-buttons/submit-for-review-button/SubmitForReviewButton.tsx
src/sections/dataset/dataset-files/dataset-upload-files-button/DatasetUploadFilesButton.tsx
src/sections/dataset/dataset-files/file-criteria-form/FileCriteriaForm.tsx
src/sections/dataset/dataset-files/files-table/file-actions/edit-files-menu/EditFilesMenu.tsx
src/sections/dataset/dataset-files/files-table/file-actions/file-actions-cell/file-action-buttons/file-options-menu/FileOptionsMenu.tsx
src/users/domain/models/User.ts
src/users/infrastructure/repositories/UserJSDataverseRepository.ts
tests/component/dataset/domain/models/DatasetMother.ts
tests/component/dataset/infrastructure/mappers/JSDatasetMapper.spec.ts
tests/component/sections/dataset/dataset-action-buttons/edit-dataset-menu/EditDatasetMenu.spec.tsx
tests/component/sections/dataset/dataset-action-buttons/publish-dataset-menu/PublishDatasetMenu.spec.tsx
tests/component/sections/dataset/dataset-action-buttons/submit-for-review-button/SubmitForReviewButton.spec.tsx
tests/component/users/domain/models/UserMother.ts
tests/e2e-integration/integration/datasets/DatasetJSDataverseRepository.spec.ts
tests/e2e-integration/integration/users/infrastructure/repositories/UserJSDataverseRepository.spec.ts
tests/e2e-integration/shared/datasets/DatasetHelper.ts

This PR adds the integration of the SPA with the js-dataverse implementation to get the dataset locks.
- Closes #206 
I didn't add an e2e test because the integration + unit tests seemed enough.
1. Run `npm I`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh unstable`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataset
4. Force a publication lock in the dataset using `curl -H "X-Dataverse-key: $API_TOKEN" -X POST …

206 - Integration dataset locks

---

tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx

In the e2e test, the Dataset tests are sometimes failing because the page is asynchronously updated during the Cypress call to click the AccessFileMenu.  To avoid this, the Cypress command for finding the button and the call to click the button are separated into two statements.
here is Cypress documentation on the issue: https://docs.cypress.io/guides/references/error-messages#cy-failed-because-the-page-updated
- Closes #236 
Due to the timing nature of the error, it's hard to reproduce consistently.  I was able to get my local dev environment in a state where it was happening by adding some console.log statements, and when I applied the fix, the error no longer happened.  
Run the e2e test locally and check the e2e test on Github Actions.  
no
no

236 - Cypress timing error

---

public/locales/en/dataset.json
src/dataset/domain/models/Dataset.ts
src/dataset/infrastructure/mappers/JSDatasetMapper.ts
src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
src/files/domain/models/File.ts
src/sections/dataset/dataset-action-buttons/DatasetActionButtons.tsx
src/sections/dataset/dataset-action-buttons/access-dataset-menu/AccessDatasetMenu.tsx
src/stories/dataset/dataset-action-buttons/access-dataset-menu/AccessDatasetMenu.stories.tsx
tests/component/dataset/domain/models/DatasetMother.ts
tests/component/dataset/infrastructure/mappers/JSDatasetMapper.spec.ts
tests/component/sections/dataset/dataset-action-buttons/access-dataset-menu/AccessDatasetMenu.spec.tsx
tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx
tests/e2e-integration/integration/datasets/DatasetJSDataverseRepository.spec.ts

This PR adds the integration to download the dataset using the Dataverse API. With this integration the user would be able to download the dataset both in original and archival formats using the Access Dataset button in the Dataset page.
- Closes #244 
1. Run `npm I`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh unstable`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataset
4. Upload some files to the dataset
5. From the dataset view …

244 - Integration download dataset

---

src/index.tsx
src/stories/WithI18next.tsx

This PR removes the loading text that appears when accessing the SPA.
- Closes #279 
The loading message was a placeholder for the React Suspense fallback. This fallback exists to give some feedback to the user about the page being loaded but it didn't seem to be necessary since we don't have long loading times and there is already a loading indicator when accessing any SPA page
Check the video to see the loading text appearing:
https://github.com/IQSS/dataverse-frontend/assets/17010447/60c11a1e-6ad3-4827-861c-1655a5ebb651
1. Run `npm I`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh unstable`
8. To check the …

279 - Fix remove loading text

---

package-lock.json
package.json
src/files/infrastructure/FileJSDataverseRepository.ts
tests/e2e-integration/integration/files/FileJSDataverseRepository.spec.ts

This PR adds the integration of the UI with the js-dataverse implementation to get the file citation.
- Closes #312 
1. Run `npm I`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh unstable`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataset
4. Upload a file to the dataset
5. From the dataset view mode click on some file to go to the File Page in JSF
6. From the url copy the fileId number
7. Go to <http://localhost:8000/spa/files> and …

312 - Integration file citation

---

README.md
lerna.json
package-lock.json
packages/design-system/CHANGELOG.md
packages/design-system/package.json

This PR updates the package.json of the design system with the new version 1.1.0. [@iqss/dataverse-design-system](https://www.npmjs.com/package/@iqss/dataverse-design-system/v/1.1.0) 
Also I added some instructions to the README on how to publish a new version.
A part from that I added a preset to lerna so the CHANGELOG.md is automatically updated with the new commits since the last version. See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
- Closes #313
The automation of the publishing will be developed in this other issue:
- #140
The creation of a test registry will be developed in this other issue:
- #144
To test the package:
1. Create a [new React application](https://react.dev/learn/start-a-new-react-project). I'll go with the first option which is …

313 - Release design system npm package version 1.1.0

---

public/locales/en/createDataset.json
public/locales/en/dataset.json
src/alert/domain/models/Alert.ts
src/sections/create-dataset/CreateDatasetForm.tsx
src/sections/create-dataset/useCreateDatasetForm.tsx
src/sections/dataset/Dataset.tsx
src/sections/dataset/DatasetFactory.tsx
src/stories/dataset/Dataset.stories.tsx
tests/component/create-dataset/CreateDatasetForm.spec.tsx
tests/component/sections/dataset/dataset-alerts/DatasetAlerts.spec.tsx
tests/e2e-integration/e2e/sections/create-dataset/CreateDatasetForm.spec.tsx

- Closes #339
Sometimes the e2e getTotalDatasetsCount() fails, because of this issue: https://github.com/IQSS/dataverse-frontend/issues/294
Review Dataset 'Created' Story, Create a Dataset and check for Validation Alerts for missing required fields, and check for Success message on Dataset Page after dataset is created.
see mockups in #339

339 add alerts for create dataset

---

public/locales/en/pagination.json
src/sections/shared/pagination/PaginationResultsInfo.tsx
tests/component/sections/shared/pagination/PaginationResultsInfo.spec.tsx

Formats the total number of items of the pagination result according to the user's preferred language. Applied to locales/en/pagination
Closes #330 
Storybook (There are additional areas that can be viewed too)
Sample URL 1: http://localhost:6006/?path=/story/sections-dataset-page-datasetfiles--no-filters
Cypress
Relating tests found in PaginationResultsInfo.spec.tsx
See Issue #330 

Feat: Add pagination total results

---

README.md

Adds a link to current SPA 2024 Q2 Milestone the Roadmap documentation. I also added a reference section for the original Dataverse Rearchitecture document.
Closes #378 
You can look at the documentation in the branch 
https://github.com/IQSS/dataverse-frontend/tree/378-spa-milestones-doc?tab=readme-ov-file#roadmap

378 spa milestones doc

---

tests/e2e-integration/e2e/sections/collection/Collection.spec.ts
tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx
tests/e2e-integration/e2e/sections/file/File.spec.tsx
tests/e2e-integration/integration/datasets/DatasetJSDataverseRepository.spec.ts
tests/e2e-integration/integration/files/FileJSDataverseRepository.spec.ts
tests/e2e-integration/shared/DataverseApiHelper.ts
tests/e2e-integration/shared/collection/CollectionHelper.ts
tests/e2e-integration/shared/datasets/DatasetHelper.ts
tests/e2e-integration/shared/files/FileHelper.ts
tests/support/commands.tsx

**What this PR does / why we need it**: Then e2e tests were sometimes failing because the destroyAll() method does not always clear the solr index correctly.  Rather than always calling destroyAll(), the tests were updated to create datasets in separate collections, where necessary, so that dataset counts are not affected by the order of tests.
Closes #387 
Run the e2e test locally `npm run test:e2e`
Check that then e2e test in Github action succeeds

387 Fix Race Condition in e2e tests

---

src/dataset/infrastructure/mappers/JSDatasetMapper.ts
tests/component/dataset/infrastructure/mappers/JSDatasetMapper.spec.ts

fix the mapping of Hierarchy in the getDataset() usecase
Closes #403 
I think this is the fix that is needed rather than https://github.com/IQSS/dataverse-client-javascript/issues/154.  
In the SPA, create a Dataset, then go to File Upload page.  The Dataset Breadcrumb on the File upload page should have the correct link.

fix: map jsDataset.id and persistentId in JSDatasetMapper.toHierarachy()

---

src/sections/collection/Collection.tsx
src/stories/create-dataset/CreateDataset.stories.tsx

Fix bug about datasets from collection not changing when collection changed.
Closes #408 
Navigate to a dataset in a sub-collection, then click on the breadcrumbs to go to the parent collection for that dataset.
The datasets in that collection will be displayed, and then click on the breadcrumb root to display the new datasets in the root collection.
No.
No.
No.

Fix - Collection page datasets not being refetched after navigating from a sub collection.

---

src/metadata-block-info/domain/models/fieldValidations.ts
src/sections/create-dataset/CreateDataset.tsx
src/sections/create-dataset/DatasetForm.module.scss
src/sections/create-dataset/DatasetForm.tsx
src/sections/create-dataset/MetadataBlockFormFields/MetadataFormField/Fields/PrimitiveMultiple.tsx
src/sections/create-dataset/MetadataBlockFormFields/index.tsx
src/sections/create-dataset/useCreateDatasetForm.tsx
tests/component/metadata-block-info/domain/models/MetadataBlockInfoMother.ts
tests/component/sections/create-dataset/CreateDataset.spec.tsx

Fixes a mismatch between the email validation of the SPA Dataset creation form and the email validation of the dataverse api.
Also improves the UX to display the alert error banner only when creations fail, with messages specific to both the client-javascript api wrapper and the dataverse api itself (from the latter extracting only the field-related part of the error and not the part of the error related to Java invalid value exceptions).
Closes #393 
Enter an invalid email (test@test.e) and check that the error message is displayed below the field.
It is a bit difficult to test the error messages in the banners as the validations are being …

Fix/393 Match api email validation

---

src/dataset/domain/models/Dataset.ts
src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
src/sections/collection/datasets-list/dataset-card/DatasetCardHeader.tsx
src/sections/shared/form/DatasetMetadataForm/useSubmitDataset.ts
tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx
tests/e2e-integration/integration/datasets/DatasetJSDataverseRepository.spec.ts
tests/e2e-integration/integration/files/FileJSDataverseRepository.spec.ts

**What this PR does / why we need it**: 
Changes the default dataset version requested from :latest to :latest-published.  This is needed to match the behavior of the JSF.  In the JSF, If a dataset has a draft version and a published version,  View Dataset page shows the published version by default (when there isn't a version search param in the url).
Closes #321 
**Special notes for your reviewer**:  
Now that the default version is :latest-published, in order to view the draft version of a dataset, you need to add 'version=DRAFT' to the view dataset url.  (The draft version used to be displayed by default when the user has permission to view it).
Create a dataset that has a published version and a draft version. …

321 default dataset version

---

.github/CONTRIBUTING.md

As reported at https://dataverse.zulipchat.com/#narrow/stream/446770-docs/topic/Dataverse-frontend.20contributing.20guideline/near/462347626 links to LICENSE and DEVELOPER_GUIDE.md are broken.

Fix links in CONTRIBUTING.md

---

.github/workflows/test.yml
public/locales/en/footer.json
src/sections/layout/footer/Footer.tsx
tests/component/sections/layout/footer/Footer.spec.tsx

There is the _Copyright @ 2023_ hardcoded in the SPA footer, but it's expected the year 2023 could always be updated to current year.
- Closes #487 
- Check if the SPA pages always display the current year in the footer right behind _copyright @_
No

487 display current year for copyright in footer

---

README.md

Updates the README file with demo link

Update README with demo link

---

.github/workflows/test.yml
src/sections/shared/form/DatasetMetadataForm/MetadataForm/index.tsx
tests/component/sections/shared/dataset-metadata-form/DatasetMetadataForm.spec.tsx

The pre-filled author and point of contact name format should be aligned with the watermark and JSF. It changes from **First Name Last Name** to **Last Name, First Name** in Create Dataset page.
- Closes #436 
Please check if the pre-filled Author name and Point of contact name is in the right format **Last Name, First Name**, in Create Dataset page.
No

436 prefill name for author and point of contact should be familyname givenname format

---

DEVELOPER_GUIDE.md
src/sections/Route.enum.ts
src/sections/create-dataset/CreateDatasetFactory.tsx
src/sections/layout/header/LoggedInHeaderActions.tsx
src/sections/shared/add-data-actions/AddDataActionsButton.tsx
tests/component/sections/shared/add-data-actions/AddDataActionsButton.spec.tsx
tests/e2e-integration/e2e/sections/create-dataset/CreateDatasetForm.spec.tsx

We decided to modify the URL path for the 'create dataset' page to maintain consistency with the 'create collection' structure. 
The changes are as follows:
Old path: /spa/datasets/create?collectionId=[collectionId]
New path: /spa/datasets/[collectionId]/create
- Closes #485 
Originally, we have /spa/datasets/create could be accessible, but after updating, it wouldn't work.
1. Click the header "Add Data" => "New Dataset", check if the url is correct
2. On the main page, click the button"+ Add Data" => "New Dataset", check if the url is correct
No
No
The Developer_Guide doc changes, because this change relates to a testing example shown on the developer guide.

485 create dataset url

---

src/sections/dataset/dataset-action-buttons/link-dataset-button/LinkDatasetButton.tsx
tests/e2e-integration/integration/datasets/DatasetJSDataverseRepository.spec.ts

The test case of getByPersistentId should also work for deaccessioned datasets. The it.skip() should be removed because the JS dataverse has included deaccessioned api. 
- Closes #535 
It would be fine if e2e test DatasetJSDataverseRepository running well with no error message.

Remove the skip from e2e test for getByPersistentId, so the test case could be included

---

src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts

It was a todo task waiting for the implementation of getbyprivateurltoken from js-dataverse side. Since the implementation is done, we are able to remove some hard-coded part with the results from api.
- Closes #536 
Run the e2e test for DatasetJSDataverseRepository
No
No

536 remove the hard coded part in getbyprivateurltoken in datasetjsdataverserepo

---

src/sections/dataset/dataset-files/files-table/file-info/file-info-cell/file-info-data/FileDate.tsx
src/sections/file/file-embargo/FileEmbargoDate.tsx
src/sections/file/file-metadata/FileMetadata.tsx
tests/component/sections/dataset/dataset-files/files-table/files-info/file-info-cell/file-info-data/FileDate.spec.tsx
tests/component/sections/file/file-embargo/FileEmbargoDate.spec.tsx
tests/component/sections/file/file-metadata/FileMetadata.spec.tsx
tests/e2e-integration/e2e/sections/dataset/Dataset.spec.tsx

For solving some existing todos, add time tag to the date so as to provides semantic meaning to the content. The date attribute within the <time> tag allows you to provide a machine-readable format of the date and time, which can be useful for search engine optimization (SEO), calendar integration, and other purposes. Also, in order to keep constant with JSF, we need change some date format to YYYY-MM-DD as well.
- Closes #533 
Step 1: Run the Development Environment
1. Execute npm i.
2. Navigate with cd packages/design-system && npm run build.
3. Return with cd ../../.
4. Ensure you have a .env file similar to .env.example, with the variable VITE_DATAVERSE_BACKEND_URL=http://localhost:8000/.
5. Navigate with cd dev-env.
6. Start the environment using ./run-env.sh unstable.
7. To verify …

Add time tag to the date and change some date format to YYYY-MM-DD

---

.github/workflows/deploy-beta-testing.yml
.github/workflows/deploy.yml
.github/workflows/test.yml
src/App.tsx
tests/component/sections/dataset/Dataset.spec.tsx

Updates download and upload artifacts to version 4.
upload-artifacts have been updated in the following workflows:
- deploy.yml
- deploy-beta-testing.yml
- test.yml
download-artifacts have been updated in the following workflows:
- deploy.yml
- deploy-beta-testing.yml
- Closes #537 
Visual code inspection and re-run the **_test_** action. 
`deploy.yml` workflow has not been used.
`deploy-beta-testing.yml` workflow has been already tested deploying this current branch and it can be checked again after merging this branch into develop.
**_Note:_** the code coverage (coverall report) says it has decreased but it is the same rare problem that keeps occurring sometimes, we should not worry about it on this issue.
No
No
No

Upgrade to v4 download and upload artifacts

---

package-lock.json
package.json

This PR adds a typecheck script to the lint script.
It also updates Typescript to the latest version so it can Types Union Props that was causing the error.
- Closes #570 
**Step 1: Run the Development Environment**
1. Execute `npm i`.
2. Navigate with `cd packages/design-system && npm i && npm run build`.
3. Return with `cd ../../`.
4. Ensure you have a `.env` file similar to `.env.example`, with the variable `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000`.
5. Navigate with `cd dev-env`.
6. Start the environment using `./run-env.sh unstable`.
7. To verify the environment, visit <http://localhost:8000> and check your local Dataverse installation.
**Step 2: Test the fix**
Change something in the code that will throw a type error and then run `npm run lint` to validate that shows the …

Fix Edit collection page type errors

---

package.json

Remove unit and integration tests from the pre-commit hook so that commits don't take as long
- Closes #556 
Review the code change and optionally do a local commit
No
No

remove unit and integration tests from pre-commit hook

---

src/sections/upload-dataset-files/uploaded-files-list/UploadedFiles.tsx
src/sections/upload-dataset-files/uploaded-files-list/files-header/FilesHeader.tsx
src/sections/upload-dataset-files/uploaded-files-list/restriction-modal/RestrictionModal.tsx
tests/component/sections/upload-dataset-files/UploadDatasetFiles.spec.tsx

Updates UploadDatasetFiles.spec.tsx to avoid race condition errors.
- Closes #481 
I wasn't able to consistently produce this error, so it's hard to tell if this will definitively fix the bug. But there were multiple places where the test referred to a checkbox by the order on the page, not by an id, which could produce problems since the RestrictedModal and the UploadedFiles component both contain multiple checkboxes.
I added a test that the RestrictedModel is closed, and I added testids to multiple elements to make sure the correct checkboxes are being tested.
Review the code, run locally and check the Github actions.
No
No

Fix UploadDatasetFiles Component test

---

package-lock.json
package.json
src/dataset/infrastructure/mappers/JSDatasetPreviewMapper.ts

For Q4.2, the goal is to complete the missing information on the cards in collection page. There is no thumbnails to items so we need add them.
- Closes #579 
The tests are written already, so there is no test added. [DatasetCardThumbnail.spec.tsx](https://github.com/IQSS/dataverse-frontend/blob/develop/tests/component/sections/collection/collection-items-panel/dataset-card/DatasetCardThumbnail.spec.tsx)
package.json should be removed after js-dataverse version updated
- create a dataset in SPA
- add a thumbnail from JSF
- test if the thumbnail for the dataset is shown in SPA
Yes, in collection page, if there is a thumbnail uploaded by user, then the dataset thumbnail should be shown.
No

Collection page: add dataset thumbnail to the item card

---

DEVELOPER_GUIDE.md

remove ```bash to fix links lower down

---

README.md

Docs for Keycloak Deployment

---

src/sections/shared/form/EditCreateCollectionForm/CollectionFormHelper.ts
src/sections/shared/form/EditCreateCollectionForm/collection-form/CollectionForm.tsx
src/sections/shared/form/EditCreateCollectionForm/collection-form/useSubmitCollection.ts
src/sections/shared/form/EditCreateCollectionForm/types.ts
tests/component/sections/shared/edit-create-collection-form/CollectionFormHelper.spec.ts

When creating a collection or an input level, we need to only send input levels that changed from its original value so we don't save unneeded data in db.
- Closes #628 
Check that create and edit collection functionality keeps working correctly.
This is just a change to send only the input levels that were modified from the original form value when editing or creating a collection.
No
No
No

Send only input levels that changed

---

package-lock.json
package.json
src/dataset/domain/models/DatasetVersionDiff.ts
src/dataset/domain/repositories/DatasetRepository.ts
src/dataset/domain/useCases/getDatasetVersionDiff.ts
src/dataset/infrastructure/mappers/JSDatasetMapper.ts
src/dataset/infrastructure/repositories/DatasetJSDataverseRepository.ts
tests/component/dataset/infrastructure/mappers/JSDatasetMapper.spec.ts

This PR integrates an update to getDatasetVersionDiff use case, which adds an `includeDeaccessioned `param.  The logic is needed to determine whether publishing the draft will require a major version number update.  After a Dataset is deaccessioned, the next version is required to be a major version update.
- Closes #650 #651 #620
1. Create a dataset, publish it, then deaccession it
2. Edit the dataset to create a draft version
3. The Dataset page showing the draft version should display correctly
4. Choose Publish Dataset to view the Publish Dataset Modal.  The Publish modal should show that a major version number update is required.
No

Fix Dataset Page showing draft version after deaccession

---

src/sections/dataset/dataset-metadata/dataset-metadata-fields/DatasetMetadataFieldValueFormatted.tsx
tests/component/sections/dataset/dataset-metadata/DatasetMetadata.spec.tsx
tests/component/sections/dataset/dataset-metadata/DatasetMetadataFieldValueFormatted.spec.tsx

The new SPA implementation shows several issues and inconsistencies in how citation metadata is displayed compared to the older JSF version. These discrepancies affect user experience and metadata accuracy.
1. add hyperlink to Alternative URL
2. use semicolon separate objects, Time Period and Data of Collections, then replace the name to Start Date and End Date accordingly
3. use colon separates Series, Contributors, Funding info , Other Identifier
4. change version formatting with comma, and keyword 'Version: 4.0'
- Closes #634

Dataset Metadata: update formats of fields

---

src/sections/dataset/DatasetSkeleton.tsx
src/sections/dataset/dataset-action-buttons/edit-dataset-menu/EditDatasetMenu.tsx
src/sections/dataset/dataset-action-buttons/edit-dataset-menu/EditDatasetPermissionsMenu.tsx
src/sections/dataset/dataset-action-buttons/submit-for-review-button/SubmitForReviewButton.tsx

- Dataset page skeleton should show four tabs while loading
- Add `Not implemented modal` to edit dataset actions
- Closes #665 
- After publishing dataset, check if there are four tabs shown (Files, Metadata, Terms, Versions)
- Check the Edit Dataset => if something is not implemented, should show Not implemented modal

Dataset Page:  update Tab skeleton

---

package-lock.json
package.json
public/locales/en/signUp.json
src/info/infrastructure/repositories/DataverseInfoJSDataverseRepository.ts
src/sections/sign-up/SignUp.tsx
src/sections/sign-up/SignUpFactory.tsx
src/sections/sign-up/valid-token-not-linked-account-form/FormFields.module.scss
src/sections/sign-up/valid-token-not-linked-account-form/FormFields.tsx
src/sections/sign-up/valid-token-not-linked-account-form/ValidTokenNotLinkedAccountForm.tsx
src/sections/sign-up/valid-token-not-linked-account-form/useSubmitUser.ts
src/shared/core/domain/models/PublicationStatus.ts
src/shared/hooks/useGetTermsOfUse.ts
src/stories/shared-mock-repositories/info/DataverseInfoMockErrorRepository.ts
src/stories/sign-up/SignUp.stories.tsx
tests/component/info/models/TermsOfUseMother.ts
tests/component/sections/sign-up/SignUp.spec.tsx
tests/component/sections/sign-up/valid-token-not-linked-account-form/ValidTokenNotLinkedAccountForm.spec.tsx
tests/component/shared/hooks/useGetTermsOfUse.spec.ts

Integrate the js-dataverse `GetApplicationTermsOfUse` use case.
After a successful OIDC login from the SPA, an account linking / complete information screen is displayed. At that point, we need to display the Installation Terms Of Use.
- Closes #674 
⚠️ ~The js-dataverse package is using a PR version, after https://github.com/IQSS/dataverse-client-javascript/pull/296 is merged we need to update package version to use alpha~.
Step 1: Run the Development Environment
1. Execute npm i.
2. Navigate with cd packages/design-system && npm i && npm run build.
3. Return with cd ../../.
4. Ensure you have a .env file similar to .env.example
5. Navigate with cd dev-env.
6. Before running next step, be sure have a fresh unstable dataverse image.
7. Start the environment using ./run-env.sh unstable.
8. …

Integrate get application terms of use in account linking

---

src/sections/homepage/Homepage.module.scss
src/sections/homepage/Homepage.tsx

Rearrange the elements of the home page so that on mobile screens the search bar appears at the top.
- Closes #684 
Validate that on mobile screens (375px) the search bar is shown at the top and on desktop screens it is shown in the middle as it is currently shown in beta.
Yes.
No
No

Rearrange Homepage elements on mobile to show search on top

---

public/locales/en/editCollectionFeaturedItems.json
src/sections/edit-collection-featured-items/featured-items-form/FeaturedItemsFormHelper.ts
src/sections/edit-collection-featured-items/featured-items-form/featured-item-field/FeaturedItemField.module.scss
src/sections/edit-collection-featured-items/featured-items-form/featured-item-field/ImageField.tsx
src/sections/featured-item/featured-item-view/FeaturedItemView.module.scss
tests/component/collection/domain/models/CollectionFeaturedItemMother.ts
tests/component/sections/edit-collection-featured-items/FeaturedItemsForm.spec.tsx
tests/component/sections/edit-collection-featured-items/FeaturedItemsFormHelper.spec.ts

This PR adds, in the Edit Collection Featured Items page:
- A helper text below the Image field about the recommended aspect ratio.
- Displays a warning message if the aspect ratio of the selected image is not the recommended one.
- Closes #690 
Step 1: Run the Development Environment
1. Execute npm i.
2. Navigate with cd packages/design-system && npm i && npm run build.
3. Return with cd ../../.
4. Ensure you have a .env file similar to .env.example
5. Navigate with cd dev-env.
6. Before running next step, be sure have a fresh unstable dataverse image.
7. Start the environment using ./run-env.sh unstable.
8. To verify the environment, visit http://localhost:8000/ and check your local Dataverse installation.
Step 2: Test the feature
1. Log in and navigate to create a featured item within …

Featured Items aspect ratio recommendations

---

src/router/ProtectedRoute.tsx

I've addressed an issue where the app loading spinner was unexpectedly appearing during background authentication token refreshes. This was causing the current page state to reset, which could interrupt users who were in the middle of tasks like filling out forms.
This fix should prevent that interruption.
To easily test this, open the Keycloak admin panel, select the Test instance,  and modify the Access Token Lifespan duration to 10 or 20 seconds (it's set to 5 minutes).
Next, open your browser's developer tools and navigate to the network tab. You should observe that a new token is fetched every 10/20 secs. To verify the persistence of form data, navigate to a page with form fields, such as the "Create collection" page. Enter some values into the fields and confirm that these values …

Fix: avoid showing app loader when refreshing token

---

.github/workflows/deploy.yml

Redesigned the deploy.yml GitHub Action to support on-demand deployments using workflow_dispatch. The new version lets us deploy any branch to either the beta or QA environment. It automatically applies the right settings based on the selected environment. The old S3 deployment option was removed due to lack of use.
- Related to #679, but does not close it.
Tested in my fork repo: https://github.com/GPortas/dataverse-frontend/actions/runs/15028028064 after configuring QA secrets with same values as in the main dataverse-frontend repo.
N/A
No
N/A

Beta and QA on-demand deployment action

---

dev.Dockerfile
src/sections/account/Account.tsx
tests/component/sections/account/Account.spec.tsx

Keeps in sync the selected tab in the Account page with the tab query param in the URL.
Note also I just modified the docker file because we had these warnings from Docker, now they are gone:
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match
- StageNameCasing: Stage name 'BUILD_IMAGE' should be lowercase
- Closes #712

Keep account tabs in sync with tab query param in the URL
